---
apiVersion: v1
kind: ConfigMap
data:
  COLAB_DATABASE_NAME: {{ .Values.db.name }}
  COLAB_DATABASE_USER: {{ .Values.db.user }}
metadata:
  name: {{ template "colab.fullname" . }}-hard-config
  labels:
    app: {{ template "colab.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: v1
data:
  COLAB_DATABASE_PASSWORD: {{ .Values.db.password | b64enc }}
kind: Secret
metadata:
  name: {{ template "colab.fullname" . }}-secret
  labels:
    app: {{ template "colab.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque

