ingress:
  enabled: false
  hostname: ""
colab:
  image_tag: 
  replicas: 1
  java_heap: 500
  min_threads: 
  max_threads: 
  smtp:
    domain: "colab.local"
    auth: true
    username: ""
    password: ""
    host: ""
    post: 587
    starttls: true
  admin:
    username: admin
    password: admin
    email: admin@colab.local
  extraproperties: |
    colab.localaccount.showcreatebutton=false
db:
  name: colab
  user: colab
  password: colab
  useExistingClaim: false
  existingClaim: ""
  size: 10Gi
mongo:
  useExistingClaim: false
  existingClaim: ""
  size: 10Gi
